package com.alkaid.proto;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data.proto

public final class Data {
  private Data() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DataPointOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DataPoint)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 序号
     * </pre>
     *
     * <code>int64 index = 1;</code>
     * @return The index.
     */
    long getIndex();

    /**
     * <pre>
     * 毫秒级时间戳
     * </pre>
     *
     * <code>double time = 2;</code>
     * @return The time.
     */
    double getTime();

    /**
     * <pre>
     * 二维数据列表
     * </pre>
     *
     * <code>repeated double data = 3;</code>
     * @return A list containing the data.
     */
    java.util.List<java.lang.Double> getDataList();
    /**
     * <pre>
     * 二维数据列表
     * </pre>
     *
     * <code>repeated double data = 3;</code>
     * @return The count of data.
     */
    int getDataCount();
    /**
     * <pre>
     * 二维数据列表
     * </pre>
     *
     * <code>repeated double data = 3;</code>
     * @param index The index of the element to return.
     * @return The data at the given index.
     */
    double getData(int index);

    /**
     * <pre>
     * 可选的二维掩码列表
     * </pre>
     *
     * <code>repeated int32 mask = 4;</code>
     * @return A list containing the mask.
     */
    java.util.List<java.lang.Integer> getMaskList();
    /**
     * <pre>
     * 可选的二维掩码列表
     * </pre>
     *
     * <code>repeated int32 mask = 4;</code>
     * @return The count of mask.
     */
    int getMaskCount();
    /**
     * <pre>
     * 可选的二维掩码列表
     * </pre>
     *
     * <code>repeated int32 mask = 4;</code>
     * @param index The index of the element to return.
     * @return The mask at the given index.
     */
    int getMask(int index);

    /**
     * <pre>
     * 通道数
     * </pre>
     *
     * <code>int32 C_SIZE = 5;</code>
     * @return The cSIZE.
     */
    int getCSIZE();

    /**
     * <pre>
     * 每通道特征数
     * </pre>
     *
     * <code>int32 X_SIZE = 6;</code>
     * @return The xSIZE.
     */
    int getXSIZE();
  }
  /**
   * Protobuf type {@code DataPoint}
   */
  public static final class DataPoint extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DataPoint)
      DataPointOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DataPoint.newBuilder() to construct.
    private DataPoint(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DataPoint() {
      data_ = emptyDoubleList();
      mask_ = emptyIntList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DataPoint();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Data.internal_static_DataPoint_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Data.internal_static_DataPoint_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Data.DataPoint.class, Data.DataPoint.Builder.class);
    }

    public static final int INDEX_FIELD_NUMBER = 1;
    private long index_ = 0L;
    /**
     * <pre>
     * 序号
     * </pre>
     *
     * <code>int64 index = 1;</code>
     * @return The index.
     */
    @java.lang.Override
    public long getIndex() {
      return index_;
    }

    public static final int TIME_FIELD_NUMBER = 2;
    private double time_ = 0D;
    /**
     * <pre>
     * 毫秒级时间戳
     * </pre>
     *
     * <code>double time = 2;</code>
     * @return The time.
     */
    @java.lang.Override
    public double getTime() {
      return time_;
    }

    public static final int DATA_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.DoubleList data_;
    /**
     * <pre>
     * 二维数据列表
     * </pre>
     *
     * <code>repeated double data = 3;</code>
     * @return A list containing the data.
     */
    @java.lang.Override
    public java.util.List<java.lang.Double>
        getDataList() {
      return data_;
    }
    /**
     * <pre>
     * 二维数据列表
     * </pre>
     *
     * <code>repeated double data = 3;</code>
     * @return The count of data.
     */
    public int getDataCount() {
      return data_.size();
    }
    /**
     * <pre>
     * 二维数据列表
     * </pre>
     *
     * <code>repeated double data = 3;</code>
     * @param index The index of the element to return.
     * @return The data at the given index.
     */
    public double getData(int index) {
      return data_.getDouble(index);
    }
    private int dataMemoizedSerializedSize = -1;

    public static final int MASK_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.IntList mask_;
    /**
     * <pre>
     * 可选的二维掩码列表
     * </pre>
     *
     * <code>repeated int32 mask = 4;</code>
     * @return A list containing the mask.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
        getMaskList() {
      return mask_;
    }
    /**
     * <pre>
     * 可选的二维掩码列表
     * </pre>
     *
     * <code>repeated int32 mask = 4;</code>
     * @return The count of mask.
     */
    public int getMaskCount() {
      return mask_.size();
    }
    /**
     * <pre>
     * 可选的二维掩码列表
     * </pre>
     *
     * <code>repeated int32 mask = 4;</code>
     * @param index The index of the element to return.
     * @return The mask at the given index.
     */
    public int getMask(int index) {
      return mask_.getInt(index);
    }
    private int maskMemoizedSerializedSize = -1;

    public static final int C_SIZE_FIELD_NUMBER = 5;
    private int cSIZE_ = 0;
    /**
     * <pre>
     * 通道数
     * </pre>
     *
     * <code>int32 C_SIZE = 5;</code>
     * @return The cSIZE.
     */
    @java.lang.Override
    public int getCSIZE() {
      return cSIZE_;
    }

    public static final int X_SIZE_FIELD_NUMBER = 6;
    private int xSIZE_ = 0;
    /**
     * <pre>
     * 每通道特征数
     * </pre>
     *
     * <code>int32 X_SIZE = 6;</code>
     * @return The xSIZE.
     */
    @java.lang.Override
    public int getXSIZE() {
      return xSIZE_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (index_ != 0L) {
        output.writeInt64(1, index_);
      }
      if (java.lang.Double.doubleToRawLongBits(time_) != 0) {
        output.writeDouble(2, time_);
      }
      if (getDataList().size() > 0) {
        output.writeUInt32NoTag(26);
        output.writeUInt32NoTag(dataMemoizedSerializedSize);
      }
      for (int i = 0; i < data_.size(); i++) {
        output.writeDoubleNoTag(data_.getDouble(i));
      }
      if (getMaskList().size() > 0) {
        output.writeUInt32NoTag(34);
        output.writeUInt32NoTag(maskMemoizedSerializedSize);
      }
      for (int i = 0; i < mask_.size(); i++) {
        output.writeInt32NoTag(mask_.getInt(i));
      }
      if (cSIZE_ != 0) {
        output.writeInt32(5, cSIZE_);
      }
      if (xSIZE_ != 0) {
        output.writeInt32(6, xSIZE_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (index_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, index_);
      }
      if (java.lang.Double.doubleToRawLongBits(time_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, time_);
      }
      {
        int dataSize = 0;
        dataSize = 8 * getDataList().size();
        size += dataSize;
        if (!getDataList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        dataMemoizedSerializedSize = dataSize;
      }
      {
        int dataSize = 0;
        for (int i = 0; i < mask_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(mask_.getInt(i));
        }
        size += dataSize;
        if (!getMaskList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        maskMemoizedSerializedSize = dataSize;
      }
      if (cSIZE_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, cSIZE_);
      }
      if (xSIZE_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, xSIZE_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Data.DataPoint)) {
        return super.equals(obj);
      }
      Data.DataPoint other = (Data.DataPoint) obj;

      if (getIndex()
          != other.getIndex()) return false;
      if (java.lang.Double.doubleToLongBits(getTime())
          != java.lang.Double.doubleToLongBits(
              other.getTime())) return false;
      if (!getDataList()
          .equals(other.getDataList())) return false;
      if (!getMaskList()
          .equals(other.getMaskList())) return false;
      if (getCSIZE()
          != other.getCSIZE()) return false;
      if (getXSIZE()
          != other.getXSIZE()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + INDEX_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getIndex());
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getTime()));
      if (getDataCount() > 0) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getDataList().hashCode();
      }
      if (getMaskCount() > 0) {
        hash = (37 * hash) + MASK_FIELD_NUMBER;
        hash = (53 * hash) + getMaskList().hashCode();
      }
      hash = (37 * hash) + C_SIZE_FIELD_NUMBER;
      hash = (53 * hash) + getCSIZE();
      hash = (37 * hash) + X_SIZE_FIELD_NUMBER;
      hash = (53 * hash) + getXSIZE();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Data.DataPoint parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Data.DataPoint parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Data.DataPoint parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Data.DataPoint parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Data.DataPoint parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Data.DataPoint parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Data.DataPoint parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Data.DataPoint parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Data.DataPoint parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Data.DataPoint parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Data.DataPoint parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Data.DataPoint parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Data.DataPoint prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DataPoint}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DataPoint)
        Data.DataPointOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Data.internal_static_DataPoint_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Data.internal_static_DataPoint_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Data.DataPoint.class, Data.DataPoint.Builder.class);
      }

      // Construct using Data.DataPoint.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        index_ = 0L;
        time_ = 0D;
        data_ = emptyDoubleList();
        mask_ = emptyIntList();
        cSIZE_ = 0;
        xSIZE_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Data.internal_static_DataPoint_descriptor;
      }

      @java.lang.Override
      public Data.DataPoint getDefaultInstanceForType() {
        return Data.DataPoint.getDefaultInstance();
      }

      @java.lang.Override
      public Data.DataPoint build() {
        Data.DataPoint result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Data.DataPoint buildPartial() {
        Data.DataPoint result = new Data.DataPoint(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(Data.DataPoint result) {
        if (((bitField0_ & 0x00000004) != 0)) {
          data_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.data_ = data_;
        if (((bitField0_ & 0x00000008) != 0)) {
          mask_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.mask_ = mask_;
      }

      private void buildPartial0(Data.DataPoint result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.index_ = index_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.time_ = time_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.cSIZE_ = cSIZE_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.xSIZE_ = xSIZE_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Data.DataPoint) {
          return mergeFrom((Data.DataPoint)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Data.DataPoint other) {
        if (other == Data.DataPoint.getDefaultInstance()) return this;
        if (other.getIndex() != 0L) {
          setIndex(other.getIndex());
        }
        if (other.getTime() != 0D) {
          setTime(other.getTime());
        }
        if (!other.data_.isEmpty()) {
          if (data_.isEmpty()) {
            data_ = other.data_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureDataIsMutable();
            data_.addAll(other.data_);
          }
          onChanged();
        }
        if (!other.mask_.isEmpty()) {
          if (mask_.isEmpty()) {
            mask_ = other.mask_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureMaskIsMutable();
            mask_.addAll(other.mask_);
          }
          onChanged();
        }
        if (other.getCSIZE() != 0) {
          setCSIZE(other.getCSIZE());
        }
        if (other.getXSIZE() != 0) {
          setXSIZE(other.getXSIZE());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                index_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 17: {
                time_ = input.readDouble();
                bitField0_ |= 0x00000002;
                break;
              } // case 17
              case 25: {
                double v = input.readDouble();
                ensureDataIsMutable();
                data_.addDouble(v);
                break;
              } // case 25
              case 26: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                ensureDataIsMutable();
                while (input.getBytesUntilLimit() > 0) {
                  data_.addDouble(input.readDouble());
                }
                input.popLimit(limit);
                break;
              } // case 26
              case 32: {
                int v = input.readInt32();
                ensureMaskIsMutable();
                mask_.addInt(v);
                break;
              } // case 32
              case 34: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                ensureMaskIsMutable();
                while (input.getBytesUntilLimit() > 0) {
                  mask_.addInt(input.readInt32());
                }
                input.popLimit(limit);
                break;
              } // case 34
              case 40: {
                cSIZE_ = input.readInt32();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 48: {
                xSIZE_ = input.readInt32();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long index_ ;
      /**
       * <pre>
       * 序号
       * </pre>
       *
       * <code>int64 index = 1;</code>
       * @return The index.
       */
      @java.lang.Override
      public long getIndex() {
        return index_;
      }
      /**
       * <pre>
       * 序号
       * </pre>
       *
       * <code>int64 index = 1;</code>
       * @param value The index to set.
       * @return This builder for chaining.
       */
      public Builder setIndex(long value) {
        
        index_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 序号
       * </pre>
       *
       * <code>int64 index = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearIndex() {
        bitField0_ = (bitField0_ & ~0x00000001);
        index_ = 0L;
        onChanged();
        return this;
      }

      private double time_ ;
      /**
       * <pre>
       * 毫秒级时间戳
       * </pre>
       *
       * <code>double time = 2;</code>
       * @return The time.
       */
      @java.lang.Override
      public double getTime() {
        return time_;
      }
      /**
       * <pre>
       * 毫秒级时间戳
       * </pre>
       *
       * <code>double time = 2;</code>
       * @param value The time to set.
       * @return This builder for chaining.
       */
      public Builder setTime(double value) {
        
        time_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 毫秒级时间戳
       * </pre>
       *
       * <code>double time = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        time_ = 0D;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.DoubleList data_ = emptyDoubleList();
      private void ensureDataIsMutable() {
        if (!((bitField0_ & 0x00000004) != 0)) {
          data_ = mutableCopy(data_);
          bitField0_ |= 0x00000004;
        }
      }
      /**
       * <pre>
       * 二维数据列表
       * </pre>
       *
       * <code>repeated double data = 3;</code>
       * @return A list containing the data.
       */
      public java.util.List<java.lang.Double>
          getDataList() {
        return ((bitField0_ & 0x00000004) != 0) ?
                 java.util.Collections.unmodifiableList(data_) : data_;
      }
      /**
       * <pre>
       * 二维数据列表
       * </pre>
       *
       * <code>repeated double data = 3;</code>
       * @return The count of data.
       */
      public int getDataCount() {
        return data_.size();
      }
      /**
       * <pre>
       * 二维数据列表
       * </pre>
       *
       * <code>repeated double data = 3;</code>
       * @param index The index of the element to return.
       * @return The data at the given index.
       */
      public double getData(int index) {
        return data_.getDouble(index);
      }
      /**
       * <pre>
       * 二维数据列表
       * </pre>
       *
       * <code>repeated double data = 3;</code>
       * @param index The index to set the value at.
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(
          int index, double value) {
        
        ensureDataIsMutable();
        data_.setDouble(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 二维数据列表
       * </pre>
       *
       * <code>repeated double data = 3;</code>
       * @param value The data to add.
       * @return This builder for chaining.
       */
      public Builder addData(double value) {
        
        ensureDataIsMutable();
        data_.addDouble(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 二维数据列表
       * </pre>
       *
       * <code>repeated double data = 3;</code>
       * @param values The data to add.
       * @return This builder for chaining.
       */
      public Builder addAllData(
          java.lang.Iterable<? extends java.lang.Double> values) {
        ensureDataIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, data_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 二维数据列表
       * </pre>
       *
       * <code>repeated double data = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        data_ = emptyDoubleList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.IntList mask_ = emptyIntList();
      private void ensureMaskIsMutable() {
        if (!((bitField0_ & 0x00000008) != 0)) {
          mask_ = mutableCopy(mask_);
          bitField0_ |= 0x00000008;
        }
      }
      /**
       * <pre>
       * 可选的二维掩码列表
       * </pre>
       *
       * <code>repeated int32 mask = 4;</code>
       * @return A list containing the mask.
       */
      public java.util.List<java.lang.Integer>
          getMaskList() {
        return ((bitField0_ & 0x00000008) != 0) ?
                 java.util.Collections.unmodifiableList(mask_) : mask_;
      }
      /**
       * <pre>
       * 可选的二维掩码列表
       * </pre>
       *
       * <code>repeated int32 mask = 4;</code>
       * @return The count of mask.
       */
      public int getMaskCount() {
        return mask_.size();
      }
      /**
       * <pre>
       * 可选的二维掩码列表
       * </pre>
       *
       * <code>repeated int32 mask = 4;</code>
       * @param index The index of the element to return.
       * @return The mask at the given index.
       */
      public int getMask(int index) {
        return mask_.getInt(index);
      }
      /**
       * <pre>
       * 可选的二维掩码列表
       * </pre>
       *
       * <code>repeated int32 mask = 4;</code>
       * @param index The index to set the value at.
       * @param value The mask to set.
       * @return This builder for chaining.
       */
      public Builder setMask(
          int index, int value) {
        
        ensureMaskIsMutable();
        mask_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 可选的二维掩码列表
       * </pre>
       *
       * <code>repeated int32 mask = 4;</code>
       * @param value The mask to add.
       * @return This builder for chaining.
       */
      public Builder addMask(int value) {
        
        ensureMaskIsMutable();
        mask_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 可选的二维掩码列表
       * </pre>
       *
       * <code>repeated int32 mask = 4;</code>
       * @param values The mask to add.
       * @return This builder for chaining.
       */
      public Builder addAllMask(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureMaskIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, mask_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 可选的二维掩码列表
       * </pre>
       *
       * <code>repeated int32 mask = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMask() {
        mask_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }

      private int cSIZE_ ;
      /**
       * <pre>
       * 通道数
       * </pre>
       *
       * <code>int32 C_SIZE = 5;</code>
       * @return The cSIZE.
       */
      @java.lang.Override
      public int getCSIZE() {
        return cSIZE_;
      }
      /**
       * <pre>
       * 通道数
       * </pre>
       *
       * <code>int32 C_SIZE = 5;</code>
       * @param value The cSIZE to set.
       * @return This builder for chaining.
       */
      public Builder setCSIZE(int value) {
        
        cSIZE_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 通道数
       * </pre>
       *
       * <code>int32 C_SIZE = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearCSIZE() {
        bitField0_ = (bitField0_ & ~0x00000010);
        cSIZE_ = 0;
        onChanged();
        return this;
      }

      private int xSIZE_ ;
      /**
       * <pre>
       * 每通道特征数
       * </pre>
       *
       * <code>int32 X_SIZE = 6;</code>
       * @return The xSIZE.
       */
      @java.lang.Override
      public int getXSIZE() {
        return xSIZE_;
      }
      /**
       * <pre>
       * 每通道特征数
       * </pre>
       *
       * <code>int32 X_SIZE = 6;</code>
       * @param value The xSIZE to set.
       * @return This builder for chaining.
       */
      public Builder setXSIZE(int value) {
        
        xSIZE_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 每通道特征数
       * </pre>
       *
       * <code>int32 X_SIZE = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearXSIZE() {
        bitField0_ = (bitField0_ & ~0x00000020);
        xSIZE_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DataPoint)
    }

    // @@protoc_insertion_point(class_scope:DataPoint)
    private static final Data.DataPoint DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Data.DataPoint();
    }

    public static Data.DataPoint getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DataPoint>
        PARSER = new com.google.protobuf.AbstractParser<DataPoint>() {
      @java.lang.Override
      public DataPoint parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<DataPoint> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DataPoint> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Data.DataPoint getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DataPoint_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DataPoint_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ndata.proto\"d\n\tDataPoint\022\r\n\005index\030\001 \001(\003" +
      "\022\014\n\004time\030\002 \001(\001\022\014\n\004data\030\003 \003(\001\022\014\n\004mask\030\004 \003" +
      "(\005\022\016\n\006C_SIZE\030\005 \001(\005\022\016\n\006X_SIZE\030\006 \001(\005b\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_DataPoint_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DataPoint_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DataPoint_descriptor,
        new java.lang.String[] { "Index", "Time", "Data", "Mask", "CSIZE", "XSIZE", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
